name: Package Legacy

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read

jobs:

  wheel-macos-x86_64:
    name: Build MacOS wheels (x86-64)
    runs-on: macos-13
    strategy:
      matrix:
        python-tag:
        - cp38-macosx_x86_64
        - cp39-macosx_x86_64
        - cp310-macosx_x86_64
        - cp311-macosx_x86_64
        - cp312-macosx_x86_64
        - cp313-macosx_x86_64
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true
        fetch-depth: 0
    - name: Build wheels
      uses: pypa/cibuildwheel@v3.4.1
      env:
        CIBW_ARCHS: x86_64
        CIBW_BUILD: ${{ matrix.python-tag }}
        CIBW_BEFORE_BUILD: pip install cython pytest
        CIBW_BUILD_VERBOSITY: 2
        CIBW_TEST_COMMAND: python -c "import fisher"
        CIBW_TEST_REQUIRES: importlib-resources
      with:
        output-dir: dist
    - uses: actions/upload-artifact@v7
      with:
        name: wheels-${{ matrix.python-tag }}
        path: dist/*

  wheel-legacy-linux-x86_64:
    name: Build legacy Linux wheels (x86-64, Python 3.6-3.7)
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-tag:
        - cp36-manylinux_x86_64
        - cp37-manylinux_x86_64
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true
        fetch-depth: 0
    - name: Build manylinux wheels
      uses: pypa/cibuildwheel@v2.11.4
      env:
        CIBW_ARCHS: x86_64
        CIBW_BUILD: ${{ matrix.python-tag }}
        CIBW_MANYLINUX_X86_64_IMAGE: quay.io/pypa/manylinux2014_x86_64
        CIBW_BEFORE_BUILD: pip install "cython<0.30" numpy pytest
        CIBW_BUILD_VERBOSITY: 2
        CIBW_TEST_COMMAND: python -c "import fisher"
        CIBW_TEST_REQUIRES: importlib-resources
      with:
        output-dir: dist
    - uses: actions/upload-artifact@v7
      with:
        name: wheels-${{ matrix.python-tag }}
        path: dist/*

  wheel-legacy-linux-aarch64:
    name: Build legacy Linux wheels (Aarch64, Python 3.6-3.7)
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        python-tag:
        - cp36-manylinux_aarch64
        - cp37-manylinux_aarch64
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true
        fetch-depth: 0
    - name: Build manylinux wheels
      uses: pypa/cibuildwheel@v2.11.4
      env:
        CIBW_ARCHS: aarch64
        CIBW_BUILD: ${{ matrix.python-tag }}
        CIBW_MANYLINUX_AARCH64_IMAGE: quay.io/pypa/manylinux2014_aarch64
        CIBW_BEFORE_BUILD: pip install "cython<0.30" numpy pytest
        CIBW_BUILD_VERBOSITY: 2
        CIBW_TEST_COMMAND: python -c "import fisher"
        CIBW_TEST_REQUIRES: importlib-resources
      with:
        output-dir: dist
    - uses: actions/upload-artifact@v7
      with:
        name: wheels-${{ matrix.python-tag }}
        path: dist/*

  wheel-legacy-macos-x86_64:
    name: Build legacy MacOS wheels (x86-64, Python 3.6-3.7)
    runs-on: macos-13
    strategy:
      matrix:
        python-tag:
        - cp36-macosx_x86_64
        - cp37-macosx_x86_64
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true
        fetch-depth: 0
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.11.4
      env:
        CIBW_ARCHS: x86_64
        CIBW_BUILD: ${{ matrix.python-tag }}
        CIBW_BEFORE_BUILD: pip install "cython<0.30" numpy pytest
        CIBW_BUILD_VERBOSITY: 2
        CIBW_TEST_COMMAND: python -c "import fisher"
        CIBW_TEST_REQUIRES: importlib-resources
      with:
        output-dir: dist
    - uses: actions/upload-artifact@v7
      with:
        name: wheels-${{ matrix.python-tag }}
        path: dist/*

  wheel-legacy-win-x86_64:
    name: Build legacy Windows wheels (x86-64, Python 3.6-3.7)
    runs-on: windows-2019
    strategy:
      matrix:
        python-tag:
        - cp36-win_amd64
        - cp37-win_amd64
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true
        fetch-depth: 0
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.11.4
      env:
        CIBW_ARCHS: AMD64
        CIBW_BUILD: ${{ matrix.python-tag }}
        CIBW_BEFORE_BUILD: pip install "cython<0.30" numpy pytest
        CIBW_BUILD_VERBOSITY: 2
        CIBW_TEST_COMMAND: python -c "import fisher"
        CIBW_TEST_REQUIRES: importlib-resources
      with:
        output-dir: dist
    - uses: actions/upload-artifact@v7
      with:
        name: wheels-${{ matrix.python-tag }}
        path: dist/*

  sdist:
    runs-on: ubuntu-24.04
    name: Build source distribution
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true
        fetch-depth: 0
    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: 3.12
    - name: Install build requirements
      run: python -m pip install -r ./requirements.txt setuptools
    - name: Build source distribution
      run: python setup.py sdist
    - name: Store built source distribution
      uses: actions/upload-artifact@v7
      with:
        name: sdist
        path: dist/*

  test-sdist:
    runs-on: ubuntu-24.04
    name: Test source distribution
    needs:
    - sdist
    steps:
    - name: Setup Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
    - name: Download built sdist
      uses: actions/download-artifact@v8
      with:
          name: sdist
          path: dist/
    - name: Update pip to latest version
      run: python -m pip install -U pip setuptools wheel pytest
    - name: Install built wheel
      run: python -m pip install --pre --no-binary fisher --find-links=dist fisher
    - name: Extract for tests
      run: tar xzvf dist/*.tar.gz && ls -lh && cp fisher-*/tests.py . && rm -r fisher-*
    - name: Run tests without coverage
      run: py.test tests.py

  upload:
    environment: PyPI
    runs-on: ubuntu-24.04
    name: Upload
    permissions:
      id-token: write
    needs:
    - sdist
    - test-sdist
    - wheel-macos-x86_64
    - wheel-legacy-linux-x86_64
    - wheel-legacy-linux-aarch64
    - wheel-legacy-macos-x86_64
    - wheel-legacy-win-x86_64
    steps:
    - uses: actions/download-artifact@v8
      with:
        pattern: wheels-*
        merge-multiple: true
        path: dist
    - uses: actions/download-artifact@v8
      with:
        name: sdist
        path: dist
    - uses: pypa/gh-action-pypi-publish@release/v1
      if: startsWith(github.ref, 'refs/tags')
      with:
        skip-existing: true
